services:
  - type: web
    name: shohozhishab
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: shohozhishab-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: shohozhishab-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: shohozhishab-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: shohozhishab-db
          property: password

databases:
  - name: shohozhishab-db
    databaseName: shohozhishab
    user: shohozuser
